https://github.com/jeffheaton/t81_558_deep_learning/blob/1f16da595603d04ee86e48b134c62e3f2f6603b2/t81_558_class_10_5_temporal_cnn.ipynb

In [24]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]],
    [[0],[2],[0],[2],[2],[0]]
]

In [25]:
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1,2],dtype=np.int32)

In [69]:
# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
print(y2)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [84]:
y2 =y2.reshape((7,1,4))
y2.shape

(7, 1, 4)

In [85]:
y2

array([[[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 0., 1.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 0., 1.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]]], dtype=float32)

In [87]:
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

In [88]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [89]:
model.fit(x,y2,epochs=50)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)

Epoch 1/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6894 - accuracy: 0.2857
Epoch 2/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6740 - accuracy: 0.2857
Epoch 3/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6591 - accuracy: 0.2857
Epoch 4/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6446 - accuracy: 0.2857
Epoch 5/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6307 - accuracy: 0.4286
Epoch 6/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6173 - accuracy: 0.4286
Epoch 7/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6044 - accuracy: 0.4286
Epoch 8/50
1/1 [==============================] - 0s 1ms/step - loss: 0.5919 - accuracy: 0.4286
Epoch 9/50
1/1 [==============================] - 0s 1ms/step - loss: 0.5799 - accuracy: 0.4286
Epoch 10/50
1/1 [==============================] - 0s 915us/step - loss: 0.5683 - accuracy: 0.4286
Epoch 11/50
1/1 [====================

In [90]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[1],[0],[0],[0]]] ))

2
